task_config:   # Настройки задачи
  bus_capacity: 80   # Количество людей, помещающихся в автобус
  start_date: [2019, 8, 17, 0, 0]   # Дата начала оптимизмируемого периода
  end_date: [2019, 8, 18, 0, 0]   # Дата окончания оптимизмируемого периода
optimization_parameters: # Настройки
  data_folder_path: 'data'  # Адресс папка с данными
  output_solution_path: 'solution.csv'   # Место записи решения
  output_results_path: 'scenarios/base_scenario.csv'   # Место записи данных для дашборда
  final_solution_path: 'solution_ready_to_send.csv'   # Решение для отправки на ЛБ
  time_box: 5
  model_saver:   # Настройки режим запуска
    save_model: True   # Флаг - сохранение модели
    model_path: 'pyo_model'   # Путь модели
    load_model: False   # Флаг подгрузки модели
  solver:   # Настройки солвера
    solver_path: "/usr/local/bin/cbc"   # Путь к солверу
    solver_name: 'cbc'   # Имя солвера
    logfile_path: 'SOLVE_LOG.log'   # Путь лога солвера
  solver_config:   # Конфиг солвера
    ratioGap: 0.0001   # Допустимое отклонение от потенциального оптимального решения
    sec: 7200   # Верхний предел по времени работы солвера
  #  end_date: [2019, 5, 17, 0, 5]
dashboard_parameters: # Настройки дашборда
  solutions_paths: # Список сценариев
    Базовый сценарий: 'scenarios/base_scenario.csv'
    Сценарий с дополнительными трапами: 'scenarios/additional_traps.csv'